# conda deactivate && conda remove -n elvis2 --all && cd elvis && conda env create -f environment.yml && conda activate elvis2 && mim install mmcv-full==1.7.2 mmdet==2.28.2 mmpose==0.29.0 mmpretrain
# For UFO to work, custom_ufo_test.py needs to be moved to UFO root
# For Propainter to work, inference_propainter.py needs to be replaced in ProPainter root
# For Real-ESRGAN to work, version import in Real-ESRGAN/realesrgan/__init__.py needs to be commented out
name: elvis2
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.4.0
  - conda-forge
  - defaults
  - xformers
dependencies:
  # Core
  - python=3.10
  - pip

  # Pytorch and CUDA (Using 12 for compatibility with my GPU, change as needed)
  # Explicitly specify pytorch channel and CUDA version to avoid CPU fallback
  - pytorch::pytorch=2.*
  - pytorch::torchvision=0.16.*
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.*
  - pytorch::torchtriton
  - nvidia::cuda-toolkit=12.*
  - nvidia::cuda-runtime=12.*

  # Other dependencies
  - conda-forge::pandas 
  - conda-forge::tqdm 
  - conda-forge::regex 
  - conda-forge::matplotlib
  - conda-forge::imageio
  - conda-forge::tensorboard
  - conda-forge::libstdcxx-ng
  - conda-forge::timm
  - conda-forge::openmim
  - conda-forge::pywavelets
  - conda-forge::opencv
  - conda-forge::matplotlib
  - conda-forge::scikit-image
  - conda-forge::numpy<2
  # Also requires ffmpeg, compatible conda versions are problematic, better to install system-wide

  - pip:
    - decord 
    - pytorch_msssim
    - dahuffman
    - pytorchvideo
    - lpips
    # For Real-ESRGAN
    - basicsr
    - facexlib
    - gfpgan
    # For InstantIR
    - diffusers==0.30
    - accelerate
    - datasets
    - einops
    - kornia
    - peft==0.10.0
    - pyrallis
    - tokenizers>=0.14,<0.19
    - transformers==4.36
    - gradio
    # Install repos from git
    # - git+https://github.com/sczhou/ProPainter.git
    # - git+https://github.com/MCG-NKU/E2FGVI.git
    # - git+https://github.com/xinntao/Real-ESRGAN.git
    # - git+https://github.com/ZiyuGuo99/InstantIR.git
    # - git+https://github.com/ragor114/PyTorch-Frechet-Video-Distance.git
    - git+https://github.com/emanuele-artioli/UFO.git@main