# cd elvis && conda env create -f environment.yml && conda activate elvis2 && mim install mmcv==2.1.0 mmdet==3.2.0 mmpose==1.3.2 mmpretrain
# For UFO to work, custom_ufo_test.py needs to be moved to UFO root
name: elvis2
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.4.0
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - pip

  # Pytorch and CUDA (Using 12.4 for better compatibility)
  # Explicitly specify pytorch channel and CUDA version to avoid CPU fallback
  - pytorch::pytorch=2.5.*
  - pytorch::torchvision=0.20.*
  - pytorch::torchaudio=2.5.*
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchtriton
  - nvidia::cuda-toolkit=12.4
  - nvidia::cuda-runtime=12.4

  # Other dependencies
  - conda-forge::pandas 
  - conda-forge::tqdm 
  - conda-forge::regex 
  - conda-forge::matplotlib
  - conda-forge::imageio
  - conda-forge::tensorboard
  - conda-forge::libstdcxx-ng
  - conda-forge::timm
  - conda-forge::openmim
  - conda-forge::pywavelets
  - conda-forge::opencv
  - conda-forge::matplotlib
  - conda-forge::scikit-image

  - pip:
    - decord 
    - pytorch_msssim
    - dahuffman
    - pytorchvideo
    - lpips